package MIPS_chisel

import chisel3._

object MIPSMain extends App {
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Mux2(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Adder(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Comparator(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Flopr(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Flopenr(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Flopenrc(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Mux3(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Regfile(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Signnext(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Sl2(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Alu_p(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Floprc(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Id_e(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new E_m(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Fu_ex(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Fu_id(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new M_w(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Maindec(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Imem(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Aludec(), args)
  (new chisel3.stage.ChiselStage)
    .emitVerilog(new Top(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Mips(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Ctrl(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Hazard(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Execute(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Datapath(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Dmemp(), args)
  //(new chisel3.stage.ChiselStage)
  //  .emitVerilog(new Testbench(), args)

}
